services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: roadtrip_planner
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roadtrip_planner_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roadtrip_planner"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://roadtrip_planner:password@db:5432/roadtrip_planner_development
      RAILS_ENV: development
    restart: on-failure

volumes:
  postgres_data:
  bundle_data: