services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-roadtrip_planner_production}
      POSTGRES_USER: ${POSTGRES_USER:-roadtrip_planner}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-roadtrip_planner} -d ${POSTGRES_DB:-roadtrip_planner_production}"]
      interval: 30s
      timeout: 10s
      retries: 5
    # Production PostgreSQL optimizations
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c work_mem=4MB
      -c max_connections=100
      -c random_page_cost=1.1
      -c log_statement=none
      -c log_duration=off
      -c log_min_duration_statement=5000
    networks:
      - roadtrip_network

  web:
    image: mnaray/roadtrip-planner:latest
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      RAILS_ENV: production
      POSTGRES_DB: ${POSTGRES_DB:-roadtrip_planner_production}
      POSTGRES_USER: ${POSTGRES_USER:-roadtrip_planner}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - roadtrip_network

volumes:
  postgres_data:

networks:
  roadtrip_network:
    driver: bridge